version: '3.3'

services:
  wrdoclet:
    build: 
      context: .
    image: adamslee/wrdoclet
    ports:
      - "8088:8080"
    restart: always
    volumes:
      - ./solrdata:/usr/share/wrdocletsolrdata
      - ./docdata:/usr/share/wrdocletdocdata
      - ./wrdoclethostsite:/usr/local/tomcat/webapps/wrdoclethostsite
      - ./solrPublish.py:/usr/local/solrPublish.py

volumes:
  solrdata:
  docdata:
  wrdoclethostsite: