version: '3.3'

services:
  solr:
    build: 
      context: .
      args:
        SOLR_URL: http://wrdocletdemo.winroad.net
    ports:
      - "8088:8080"
    restart: always
    volumes:
      - ./solrdata:/usr/share/wrdocletsolrdata
      - ./docdata:/usr/share/wrdocletdocdata
      - ./solrPublish.py:/usr/local/solrPublish.py
    container_name: wrdoclet

volumes:
  solrdata:
  docdata: